// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrantes.Data;

namespace Migrantes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Migrantes.Models.Entities.DatosFamiliares", b =>
                {
                    b.Property<int>("id_datos_familiares")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PersonaLinkper_codigo_id")
                        .HasColumnType("int");

                    b.Property<int>("edad_madre")
                        .HasColumnType("int");

                    b.Property<int>("edad_padre")
                        .HasColumnType("int");

                    b.Property<int>("estado_datosfamiliares")
                        .HasColumnType("int");

                    b.Property<string>("nombres_madre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres_padre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("per_codigo_id")
                        .HasColumnType("int");

                    b.Property<string>("primer_apellido_madre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primer_apellido_padre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profesion_madre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profesion_padre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundo_apellido_madre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundo_apellido_padre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_datos_familiares");

                    b.HasIndex("PersonaLinkper_codigo_id");

                    b.ToTable("datos_familiares", "mig");
                });

            modelBuilder.Entity("Migrantes.Models.Entities.EstadoCivil", b =>
                {
                    b.Property<int>("id_estado_civil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("activo")
                        .HasColumnType("int");

                    b.Property<string>("estado_civil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_estado_civil");

                    b.ToTable("estado_civil", "mig");
                });

            modelBuilder.Entity("Migrantes.Models.Entities.IdentidadPersona", b =>
                {
                    b.Property<int>("ide_id_persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreImagenPortada_A")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NombreImagenPortada_A");

                    b.Property<string>("NombreImagenPortada_B")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PersonaLinkper_codigo_id")
                        .HasColumnType("int");

                    b.Property<string>("RutaImagenPortada_A")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RutaImagenPortada_A");

                    b.Property<string>("RutaImagenPortada_B")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TipoDocumentoLinktid_id_documento")
                        .HasColumnType("int");

                    b.Property<int>("ide_codigo_id")
                        .HasColumnType("int");

                    b.Property<bool>("ide_entregado")
                        .HasColumnType("bit");

                    b.Property<int>("ide_estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("ide_fecha_emision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ide_fecha_vencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("ide_id_documento")
                        .HasColumnType("int");

                    b.Property<int>("ide_numero")
                        .HasColumnType("int");

                    b.HasKey("ide_id_persona");

                    b.HasIndex("PersonaLinkper_codigo_id");

                    b.HasIndex("TipoDocumentoLinktid_id_documento");

                    b.ToTable("ide_identidad", "mig");
                });

            modelBuilder.Entity("Migrantes.Models.Entities.Persona", b =>
                {
                    b.Property<int>("per_codigo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("per_apellido_cas")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("per_apellidos_nombres")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("per_coddep_nac")
                        .HasColumnType("int");

                    b.Property<string>("per_codigo_alternativo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("per_codmun_nac")
                        .HasColumnType("int");

                    b.Property<string>("per_codpai_digita")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("per_codpai_nacimiento")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("per_codpai_nacionalidad")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("per_edad")
                        .HasColumnType("int");

                    b.Property<string>("per_email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("per_email_interno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("per_estado")
                        .HasColumnType("int");

                    b.Property<int>("per_estado_civil")
                        .HasColumnType("int");

                    b.Property<DateTime>("per_fecha_grabacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("per_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("per_fecha_nac")
                        .HasColumnType("datetime2");

                    b.Property<string>("per_letra_indice")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("per_lugar_nac")
                        .HasColumnType("int");

                    b.Property<string>("per_nombre_usual")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("per_observaciones")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("per_otros_nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("per_primer_ape")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("per_primer_nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("per_profesion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("per_segundo_ape")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("per_segundo_nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("per_sexo")
                        .HasColumnType("int");

                    b.Property<string>("per_telefono_interno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("per_telefono_movil")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("per_usuario_grabacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("per_usuario_modificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("per_codigo_id");

                    b.ToTable("per_persona", "mig");
                });

            modelBuilder.Entity("Migrantes.Models.Entities.Sexo", b =>
                {
                    b.Property<int>("id_sexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("activo")
                        .HasColumnType("int");

                    b.Property<string>("nombre_sexo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nomenclatura_sexo")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("id_sexo");

                    b.ToTable("sexo", "mig");
                });

            modelBuilder.Entity("Migrantes.Models.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("tid_id_documento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("tid_activo")
                        .HasColumnType("int");

                    b.Property<string>("tid_descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("tid_id_documento");

                    b.ToTable("tid_tipo_documento", "mig");
                });

            modelBuilder.Entity("Migrantes.Models.Entities.TipoEstado", b =>
                {
                    b.Property<int>("tep_tipo_estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("tep_activo")
                        .HasColumnType("int");

                    b.Property<string>("tep_descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("tep_tipo_estado");

                    b.ToTable("tep_tipo_estado", "mig");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Migrantes.Models.Entities.DatosFamiliares", b =>
                {
                    b.HasOne("Migrantes.Models.Entities.Persona", "PersonaLink")
                        .WithMany()
                        .HasForeignKey("PersonaLinkper_codigo_id");

                    b.Navigation("PersonaLink");
                });

            modelBuilder.Entity("Migrantes.Models.Entities.IdentidadPersona", b =>
                {
                    b.HasOne("Migrantes.Models.Entities.Persona", "PersonaLink")
                        .WithMany("IdentidadPersonaLink")
                        .HasForeignKey("PersonaLinkper_codigo_id");

                    b.HasOne("Migrantes.Models.Entities.TipoDocumento", "TipoDocumentoLink")
                        .WithMany("IdentidadPersonaLink")
                        .HasForeignKey("TipoDocumentoLinktid_id_documento");

                    b.Navigation("PersonaLink");

                    b.Navigation("TipoDocumentoLink");
                });

            modelBuilder.Entity("Migrantes.Models.Entities.Persona", b =>
                {
                    b.Navigation("IdentidadPersonaLink");
                });

            modelBuilder.Entity("Migrantes.Models.Entities.TipoDocumento", b =>
                {
                    b.Navigation("IdentidadPersonaLink");
                });
#pragma warning restore 612, 618
        }
    }
}
